name: Upload SDK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download SDK
        run: |
          mkdir extracted_folder
          curl -LJO https://github.com/arichornlover/iPhoneOS-SDK/releases/download/v1.0/iPhoneOS18.0.sdk.zip

      - name: Unpack SDK
        run: |
          if [ -f iPhoneOS18.0.sdk.zip ]; then
            unzip iPhoneOS18.0.sdk.zip -d extracted_folder
          else
            echo "Failed to download the SDK ZIP file"
            exit 1
          fi
      
      - name: Move files
        run: mv extracted_folder/* .
      
      - name: Commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Add SDK files"
          git push
